### ISSUE TITLE
Compressed Crooks

### ISSUE THREAD

**Issue by shinauko33** [marckskl/skyworkshop#13]
So...I was using compressed crooks okay on regular leaves. (Dark oak specifically) AND Then I tried to use it on Infested leaves. And it crashed.

**Comment by marckskl** [comment]
> So...I was using compressed crooks okay on regular leaves. (Dark oak specifically) AND Then I tried to use it on Infested leaves. And it crashed. 

Have disabled until permanent fix is available.
