### ISSUE TITLE
Prosperity Ore

### ISSUE THREAD

**Issue by shinauko33** [marckskl/skyworkshop#15]
Can you confirm that prosperity ore does drop from the ore mining laser? I have had it running for 3 days now and have gotten 0.

**Comment by vertex101** [comment]
okay so i have looked through the lens for the laser drill and the prosperity ore is not on any of the lens there is actually like 4 of them that are not used for any thing so you might be able to add it to a lens color idk how the config is i havent looked at them yet

**Comment by vertex101** [comment]
@marckskl okay i have found the way to add ores to the laser drill after googling and joining IF discord but you can add ores using a datapack (i have been testing in single player) but a list of all ore recipes for IF is here https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/tree/1.16/src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore and here is the datapack i have made when testing in single player
[sws.zip](https://github.com/marckskl/skyworkshop/files/6622504/sws.zip) only thing you have to do is take that zip file put it in the datapack folder in the server world unzip and either restart the server or just reload it and the ore will be in the laser drill but you can also go through all the other recipes to see how you want to set it up https://i.imgur.com/OqWaGVn.png

**Comment by marckskl** [comment]
This has been added via datapack
