### ISSUE TITLE
Unify other cross mod items and recipes.

### ISSUE THREAD

**Issue by Silverne84** [marckskl/skyworkshop#18]
Gears: Iron, Gold, Diamond. Consider removing the ones from Titanium
Also making the recipes for those 3 create thermal ones.
Consider removing one of the recipes for gear creation on crafting grid.. No need for 2 that do same thing.. One has nug, one does not.

**Comment by marckskl** [comment]
Gears from Titanium have already been removed on the updated client. I will look into the crafting grid version.

**Comment by marckskl** [comment]
These have been fixed in the most recent client update.
