### ISSUE TITLE
Won't Let me Complete Barrel Quest

### ISSUE THREAD

**Issue by shinauko33** [marckskl/skyworkshop#20]
I have tried relogging and making new ones picking up old ones. Throwing them on the ground picking them back up. Nothing. I made 2 Oak ones.

**Comment by marckskl** [comment]
> I have tried relogging and making new ones picking up old ones. Throwing them on the ground picking them back up. Nothing. I made 2 Oak ones.

This has been fixed via a change to "Detect Crafting only" in the quest.
