### ISSUE TITLE
Quest description error

### ISSUE THREAD

**Issue by itsjusttriz** [marckskl/skyworkshop#21]
On the 1st page of Questbook, the "Flintz!" quest after achieving Gravel, the description states crafting 3 gravel gives flint, while JEI & an attempt to craft shows that is false.

Modpack v3.0.3

**Comment by marckskl** [comment]
Simple config change in Tinkers Construct. I'll look into a quick fix and get a new update out soon.

**Comment by itsjusttriz** [comment]
SeemsGood, not really an urgent update as the line is still progressable as we can sift gravel to get flint, just at a lower rate.
