### ISSUE TITLE
Uhh Quest book aint working

### ISSUE THREAD

**Issue by shinauko33** [marckskl/skyworkshop#5]
Quest book acknowledges quest is done. Does not do anything else.

**Comment by marckskl** [comment]
> Quest book acknowledges quest is done. Does not do anything else.

Is there a specific quest this happened on? Or just all quests?

**Comment by vertex101** [comment]
the whole quest book as been reset for me @marckskl and none of the quest are completing even with a 16 logs it is not completing

**Comment by shinauko33** [comment]
I can't get past the first quest so I don't know.
